# This is a basic workflow to help you get started with Actions

name: htmlCodeCoverageReport

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # SEtup MATLAB
      - name: Set up MATLAB on runner
        uses: matlab-actions/setup-matlab@v0

      # Runtests
      - name: Run Coverage
        uses: matlab-actions/run-command@v1
        with:
          command: utils.runCodeCoverage();
          
      #Add files to repository
      - name: Add-files
        if: always()
        continue-on-error: true
        run: |
          git config --global user.email "mangrakh@mathworks.com" && git config --global user.name "mukeshangrakh"
          git add test-results/*
          git add coverageReport-html/*
          git commit -m "test report captured"
          git push
